language: python

python:
  - "2.7"

install:
  - "pip install coverage nose-cover3 flake8 python-coveralls --use-mirrors"
  - "pip install -e . --use-mirrors"

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
