name: Create and Publish Release 🚀

on:
  workflow_dispatch:
    inputs:
      part:
        description: 'The part of the version to increment (patch, minor, or major)'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes and tags

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need full history to correctly calculate next version
          fetch-depth: 0
          # This token is used to push commits back to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bump-my-version pytest

      - name: Install and run tests via tox
        run: |
          pip install tox
          tox -e py

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ github.event.inputs.part }}
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Push changes and tags
        run: git push --follow-tags

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          gh release create "$TAG_NAME" --notes "New ${{ github.event.inputs.part }} release."
